
CC=gcc
CFLAGS=-Wall -g

hello: hello.c
	    $(CC) $(CFLAGS) hello.c -o hello
steady: serialsteady.c
		$(CC) $(CFLAGS) serialsteady.c -o serialsteady
read: readingandopps.c
		$(CC) $(CFLAGS) readingandopps.c -o readingandopps
bug: buggedcode.c
		$(CC) $(CFLAGS) buggedcode.c -o bugs



